### ISSUE TITLE
Splits variable names with two dashes

### ISSUE THREAD

**Issue by tinovyatkin** [mrmlnc/vscode-stylefmt#15]
Hello,
Not sure if it `stylefmt` related or extension related, but it brokes SCSS variables with two dashes in name, like `$ratio-16-9` into something wrong like `$ratio-16 - 9` (so, confuses with calculation I assume?).

Otherwise nice extension!

**Comment by mrmlnc** [comment]
@tinovyatkin,

Firstly, thank you for opening this issue. 

I can't reproduce your problem on Windows 10. Please create this question in the [repository Stylefmt](https://github.com/morishitter/stylefmt). I will update the plugin, once this issue is resolved.

You can help fix the problem, if you provide small code examples.

**Comment by tinovyatkin** [comment]
I think it's related to the [issue #195](https://github.com/morishitter/stylefmt/issues/195) at `stylefmt` so I didn't open new issue there (as it's too much already)

**Comment by mrmlnc** [comment]
Closed, because this is upstream issue. But i'll update this plugin, once #195 issue will be resolved.
