### ISSUE TITLE
Autofixing on errors

### ISSUE THREAD

**Issue by svipas** [mrmlnc/vscode-stylefmt#96]
Hello,

I know that stylelint still not released yet with `--fix` feature, but after release when also `stylefmt` will be updated to use latest version of stylelint, what do you think about fix feature on format?

If you can don't close this issue, let it be, when stylelint and stylefmt will be updated with `--fix` feature we can discuss here to include it or no.

**Comment by mrmlnc** [comment]
IMHO, this does not apply to this plugin. This should be implemented in the `stylelint` plugin.

**Comment by svipas** [comment]
@mrmlnc You're saying true, but `stylelint` plugin owner doesn't give a **** about that. By the way `prettier` is JS formatter, but it adds needed semicolons and so on, it works like `--fix`, but with extra addition, I was thinking the same for this CSS formatter, but anyway, you're saying true, this function not belongs for `stylefmt`. You can close issue if you want.

**Comment by mrmlnc** [comment]
You must to understand that they are two different entities and they are not associated. This functionality applies to Stylelint. Ideally, Stylelint must absorb Stylefmt because it uses the rules first. We can fork or send PR's to `vscode-stylelint`. I'm not going to close the issue to remember about him.

**Comment by mrmlnc** [comment]
Fixed by #162.
